- name: Install zsh | pacman
  become: yes
  become_user: root
  pacman:
    name: zsh
    state: present

- name: Install curl | pacman
  become: yes
  become_user: root
  pacman:
    name: curl
    state: present

- name: Set zsh as default shell for user | command
  become: yes
  become_user: root
  command: chsh -s /bin/zsh {{ ansible_user_id }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

- name: Check for oh-my-zsh installation | stat
  stat:
    path: "{{ home }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh | raw
  raw: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  when: not oh_my_zsh_stat.stat.exists

- name: Install zsh-syntax-highlighting | pacman
  become: yes
  become_user: root
  pacman:
    name: zsh-syntax-highlighting
    state: present
  when: not oh_my_zsh_stat.stat.exists

- name: Install fzf-zsh-plugin | command
  command: git clone https://github.com/unixorn/fzf-zsh-plugin.git "{{ home }}/.oh-my-zsh/custom/plugins/fzf-zsh-plugin"
  when: not oh_my_zsh_stat.stat.exists

- name: Install powerlevel10k | command
  command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"
  when: not oh_my_zsh_stat.stat.exists

- name: Link .zshrc home file | file
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/.zshrc_home"
    dest: "{{ home }}/.zshrc"
    state: link
    force: yes

- name: Link .zshrc file | file
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/.zshrc"
    dest: "{{ home }}/.config/zsh/.zshrc"
    state: link
    force: yes
