[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#4B5263"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#98C379"
magenta = "#C678DD"
red = "#BE5046"
white = "#3E4452"
yellow = "#D19A66"

[colors.cursor]
cursor = "#ABB2BF"
text = "#ABB2BF"

[colors.normal]
black = "#5C6370"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#98C379"
magenta = "#C678DD"
red = "#E06C75"
white = "#ABB2BF"
yellow = "#E5C07B"

[colors.primary]
background = "#282C34"
foreground = "#ABB2BF"

[colors.selection]
background = "#979EAB"
text = "#282C34"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Medium"

[window.padding]
x = 15
y = 15
