- name: Install sxhkd | pacman
  become: yes
  become_user: root
  pacman:
    name: sxhkd
    state: present

- name: Creates .config dir | file
  file:
    path: "{{ home }}/.config/sxhkd"
    state: directory

- name: Link sxhkdrc file | file
  file:
    src: "{{ dotfiles_home }}/roles/sxhkd/files/sxhkdrc"
    dest: "{{ home }}/.config/sxhkd/sxhkdrc"
    state: link
    force: yes
