- name: Install rofi | pacman
  become: yes
  become_user: root
  pacman:
    name: rofi
    state: present

- name: Creates .config dir | file
  file:
    path: "{{ home }}/.config/rofi"
    state: directory

- name: Link rofi config file | file
  file:
    src: "{{ dotfiles_home }}/roles/rofi/files/config.rasi"
    dest: "{{ home }}/.config/rofi/config.rasi"
    state: link
    force: yes
