- name: Install prerequisites | pacman
  become: yes
  become_user: root
  pacman:
    name: tmux
    state: present

- name: Check tmux plugin is installed | stat
  stat:
    path: "{{ home }}/.tmux"
  register: tmux_plugin_stat

- name: Clone tmux plugin | command
  command: git clone https://github.com/tmux-plugins/tpm "{{ home }}"/.tmux/plugins/tpm
  when: not tmux_plugin_stat.stat.exists

- name: Create tmux folder if not exists | file
  file:
    path: "{{ home }}/.config/tmux"
    state: directory

- name: Link tmux config | file
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{ home }}/.config/tmux/tmux.conf"
    state: link
    force: yes

- name: Link .tmux.conf | file
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/.tmux.conf"
    dest: "{{ home }}/.tmux.conf"
    state: link
    force: yes
