#! /bin/sh
bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color  \#ABB2BF
bspc config normal_border_color  \#5C6370
bspc config focused_border_color \#ABB2BF

bspc config top_padding          24
bspc config left_padding         0
bspc config right_padding        0
bspc config bottom_padding       0

# Open applications on specific workspaces
bspc rule -a brave-browser       desktop='^1'
bspc rule -a NeoVim              desktop='^2'
bspc rule -a Slack               desktop='^4'
bspc rule -a Spotify             desktop='^5'
bspc rule -a Dbeaver             desktop='^6'

bspc subscribe all | while read line; do polybar-msg hook title_bar 1; done &

# Start up
killall -q "sxhkd"; sleep 0.5; sxhkd &
# Load Xresources for polybar
xrdb ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
# Set background
nitrogen --restore &
