- name: Install wget | pacman
  become: yes
  become_user: root
  pacman:
    name: wget
    state: present

- name: Download Nerd fonts | raw
  raw: |
    wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/{{ item }}.zip" -P "{{ home }}/Downloads"
    unzip "{{ home }}/Downloads/{{ item }}.zip" -d "{{ home }}/.fonts/"
    rm "{{ home }}/Downloads/{{ item }}.zip"
  loop:
    - Gohu
    - JetBrainsMono
    - Arimo

- name: Refresh font cache | raw
  raw: fc-cache -f -v

