- name: Install wget | pacman
  become: yes
  become_user: root
  pacman:
    name: wget
    state: present

- name: Download Nerd fonts | raw
  raw: |
    wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/{{ item }}.zip" -P "{{ home }}/Downloads"
    unzip "{{ home }}/Downloads/{{ item }}.zip" -d "{{ home }}/.fonts/"
    rm "{{ home }}/Downloads/{{ item }}.zip"
  loop:
    - Gohu
    - JetBrainsMono
    - Arimo

- name: Install noto-fonts-emoji | pacman
  become: yes
  become_user: root
  pacman:
    name: noto-fonts-emoji
    state: present

- name: Link local conf file | file
  file:
    src: "{{ dotfiles_home }}/roles/nerd-fonts/files/local.conf"
    dest: "/etc/fonts/local.conf"
    state: link
    force: yes

- name: Refresh font cache | raw
  raw: fc-cache -f -v
