- name: Install docker and compose | pacman
  become: yes
  become_user: root
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker-compose

- name: Add user to docker | user
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes

- name: Enable and start docker service | systemd
  systemd:
    name: docker
    enabled: yes
    state: started
    masked: no
