- name: Install alacritty | pacman
  become: yes
  become_user: root
  pacman:
    name: alacritty
    state: present

- name: Creates .config dir | file
  file:
    path: "{{ home }}/.config/alacritty"
    state: directory

- name: Link alacritty.toml file | file
  file:
    src: "{{ dotfiles_home }}/roles/alacritty/files/alacritty.toml"
    dest: "{{ home }}/.config/alacritty/alacritty.toml"
    state: link
    force: yes
